name: FallenKingdoms
version: '1.0-SNAPSHOT'
main: custom_items.fallenKingdoms.FallenKingdoms
api-version: '1.21'
commands:
  createTeam:
    description: Creates a new team
    usage: /<command> <number_of_teams>
  showTeamsInfos:
    description: Show all teams info
    usage: /<command>
  addPlayerToTeam:
    description: Add a player to a team
    usage: /<command> <player> <team>
  removePlayerFromTeam:
    description: Remove a player from a team
    usage: /<command> <player> <team>
  forceAddPlayerToTeam:
    description: Force adding a player to a team by removing him from previous team
    usage: /<command> <player> <team>
  removeTeam:
    description: Remove a team by this name or all teams
    usage: /<command> <team|all>